name: final_year_project
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: 3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  curved_navigation_bar: ^1.0.6
  google_nav_bar: ^5.0.7
  lucide_icons: ^0.257.0
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.2
  intl: ^0.20.2
  file_picker: ^9.0.0
  geolocator: ^10.1.0
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/women.png
    - assets/cat.png
    - assets/dog.png
    - assets/map.png
    - assets/meow.png
    - assets/dr.neha.png
    - assets/dr.png
    - assets/pets.png
    - assets/dr.ravi.png
    - assets/khalti.png
    - assets/vaccinee.png
    - assets/profilepic.png
    - assets/account.png
